name: CI

on:
  push:
    branches: [ ci/deno ]
  pull_request:
    branches: [ main ]

jobs:
  # test:
  #   runs-on: ubuntu-latest
  #
  #   steps:
  #   - uses: actions/checkout@v4
  #
  #   - name: Install pnpm
  #     uses: pnpm/action-setup@v4
  #
  #   - name: Use Node.js 22
  #     uses: actions/setup-node@v4
  #     with:
  #       node-version: 22
  #       cache: 'pnpm'
  #
  #   - name: Install dependencies
  #     run: pnpm install --frozen-lockfile
  #
  #   - name: Build
  #     run: pnpm build
  #
  #   - name: Run tests
  #     run: |
  #       # Run tests with a timeout to prevent hanging
  #       timeout 5m pnpm test || exit_code=$?
  #       # Exit code 124 means timeout, which we'll treat as success if tests passed
  #       if [ "${exit_code:-0}" -eq 124 ]; then
  #         echo "Tests completed but process didn't exit cleanly (known issue with file handles)"
  #         exit 0
  #       else
  #         exit ${exit_code:-0}
  #       fi
  #
  #   - name: Type check
  #     run: pnpm typecheck
  #
  #   - name: Lint
  #     run: pnpm lint
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install pnpm
      uses: pnpm/action-setup@v4
    
    - name: Use Node.js 22
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'pnpm'

    - name: Deno Lsp
      uses: denoland/setup-deno@v2
      with:
        deno-version: 2.x
     
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
    
    - name: Build
      run: pnpm build
    
    - name: Run tests
      run: |
        # Run tests with a timeout to prevent hanging
        timeout 5m pnpm test || exit_code=$?
        # Exit code 124 means timeout, which we'll treat as success if tests passed
        if [ "${exit_code:-0}" -eq 124 ]; then
          echo "Tests completed but process didn't exit cleanly (known issue with file handles)"
          exit 0
        else
          exit ${exit_code:-0}
        fi
      env:
        LSP_COMMAND: "deno lsp"
